OHFmusim_multithread: OHFmusim_multithread.cc
	g++ -I/home/evan/root_with_pythia/pythia8306/include 'root-config --cflags' $@.cc -o $@ -lpythia8 -L/home/evan/root_with_pythia/pythia8306/lib 'root-config --glibs'
