OHFmusim_multithread: OHFmusim_multithread.cc
	g++ -I/home/evan/root_with_pythia/pythia8307/include `root-config --cflags` $@.cc -o $@ -lpythia8 -L/home/evan/root_with_pythia/pythia8307/lib `root-config --glibs`


OHFmusim_multithread2: OHFmusim_multithread2.cc
	g++ `root-config --cflags` $@.cc -o $@ `root-config --glibs`
